[metadata]
addr = 0x126f60
size = 0x28
last_change = 2023-11-15T17:23:34.724797Z

[header]
last_change = 2023-11-15T17:19:15.402543Z
name = "ClearHiddenModelList__12HideModelMgr"
addr = 0x126f60
type = "long"

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4
