[metadata]
addr = 0x1676c8
size = 0x6ac
last_change = 2023-11-15T17:21:06.717585Z

[header]
last_change = 2023-11-15T17:19:25.666780Z
name = "CSpecialFX::Render2DFXs"
addr = 0x1676c8
type = "long"

[stack_vars.-0x98]
offset = 0x0
name = "v30"
type = "_BYTE[16]"
size = 0x10
addr = 0x1676c8

[stack_vars.-0x88]
offset = 0x10
name = "v31"
type = "char[4]"
size = 0x4
addr = 0x1676c8

[stack_vars.-0x84]
offset = 0x14
name = "v32"
type = "char[4]"
size = 0x4
addr = 0x1676c8

[stack_vars.-0x80]
offset = 0x18
name = "v33"
type = "char[4]"
size = 0x4
addr = 0x1676c8

[stack_vars.-0x7c]
offset = 0x1c
name = "v34"
type = "char[4]"
size = 0x4
addr = 0x1676c8

[stack_vars.-0x78]
offset = 0x20
name = "v35"
type = "char[16]"
size = 0x10
addr = 0x1676c8

[stack_vars.-0x20]
offset = 0x78
name = "v36"
type = "long"
size = 0x8
addr = 0x1676c8

[stack_vars.-0x18]
offset = 0x80
name = "v37"
type = "float"
size = 0x4
addr = 0x1676c8

[stack_vars.-0x10]
offset = 0x88
name = "v38"
type = "float"
size = 0x4
addr = 0x1676c8

[stack_vars.-0x8]
offset = 0x90
name = "v39"
type = "float"
size = 0x4
addr = 0x1676c8

[stack_vars.0x0]
offset = 0x98
name = "v40"
type = "float"
size = 0x4
addr = 0x1676c8

[header.args.0]
offset = 0x0
name = "a1"
type = "long"
size = 0x8

[header.args.1]
offset = 0x1
name = "a2"
type = "long"
size = 0x8
