[metadata]
addr = 0x1790f0
size = 0x90
last_change = 2023-11-15T17:21:21.917080Z

[header]
last_change = 2023-11-15T17:19:25.749305Z
name = "CFileMgr::SetDir"
addr = 0x1790f0
type = "long"

[header.args.0]
offset = 0x0
name = "a1"
type = "long"
size = 0x8
