[metadata]
addr = 0x1a8198
size = 0xc0
last_change = 2023-11-27T05:30:03.817991Z

[header]
last_change = 2023-11-27T05:30:03.817991Z
name = "CModelInfo::Load"
addr = 0x1a8198
type = "void"

[header.args.0]
offset = 0x0
name = "a1"
type = "long"
size = 0x8

[header.args.1]
offset = 0x1
name = "a2"
type = "int"
size = 0x4
