[metadata]
addr = 0x233278
size = 0x148
last_change = 2023-11-15T17:20:18.808949Z

[header]
last_change = 2023-11-15T17:19:30.640774Z
name = "CPlayerPed::DoJumpingStuff"
addr = 0x233278
type = "long"

[stack_vars.-0x38]
offset = 0x0
name = "v10"
type = "int[8]"
size = 0x20
addr = 0x233278

[header.args.0]
offset = 0x0
name = "a1"
type = "long"
size = 0x8

[header.args.1]
offset = 0x1
name = "a2"
type = "_WORD *"
size = 0x4
