[metadata]
addr = 0x233c80
size = 0x36c
last_change = 2023-11-15T17:20:49.442872Z

[header]
last_change = 2023-11-15T17:19:30.957445Z
name = "CPlayerPed::PlayerControlSniper"
addr = 0x233c80
type = "long"

[stack_vars.-0x58]
offset = 0x0
name = "v16"
type = "float[11]"
size = 0x2c
addr = 0x233c80

[stack_vars.-0x2c]
offset = 0x2c
name = "v17"
type = "float"
size = 0x4
addr = 0x233c80

[header.args.0]
offset = 0x0
name = "a1"
type = "long"
size = 0x8

[header.args.1]
offset = 0x1
name = "a2"
type = "long"
size = 0x8
