[metadata]
addr = 0x255950
size = 0x78
last_change = 2023-11-15T17:22:41.230864Z

[header]
last_change = 2023-11-15T17:19:33.620166Z
name = "CTheScripts::StartNewScript"
addr = 0x255950
type = "long"

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4
