[metadata]
addr = 0x261be8
size = 0x788
last_change = 2023-11-15T17:22:32.462388Z

[header]
last_change = 2023-11-15T17:19:34.009487Z
name = "CFont::ParseToken"
addr = 0x261be8
type = "long"

[stack_vars.-0x68]
offset = 0x0
name = "v49"
type = "long"
size = 0x8
addr = 0x261be8

[stack_vars.-0x60]
offset = 0x8
name = "v50"
type = "float"
size = 0x4
addr = 0x261be8

[stack_vars.-0x5c]
offset = 0xc
name = "v51"
type = "int"
size = 0x4
addr = 0x261be8

[stack_vars.-0x58]
offset = 0x10
name = "v52"
type = "int"
size = 0x4
addr = 0x261be8

[stack_vars.-0x54]
offset = 0x14
name = "v53"
type = "int"
size = 0x4
addr = 0x261be8

[header.args.0]
offset = 0x0
name = "a1"
type = "long"
size = 0x8

[header.args.1]
offset = 0x1
name = "a2"
type = "long"
size = 0x8

[header.args.2]
offset = 0x2
name = "a3"
type = "long"
size = 0x8

[header.args.3]
offset = 0x3
name = "a4"
type = "long"
size = 0x8

[header.args.4]
offset = 0x4
name = "a5"
type = "long"
size = 0x8

[header.args.5]
offset = 0x5
name = "a6"
type = "long"
size = 0x8

[header.args.6]
offset = 0x6
name = "a7"
type = "long"
size = 0x8

[header.args.7]
offset = 0x7
name = "a8"
type = "int"
size = 0x4
