[metadata]
addr = 0x27bff8
size = 0x310
last_change = 2023-11-15T17:22:15.381785Z

[header]
last_change = 2023-11-15T17:19:34.133517Z
name = "CRegisteredCorona::Update"
addr = 0x27bff8
type = "unsigned long"

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4
