[metadata]
addr = 0x286af0
size = 0x2c
last_change = 2023-11-15T17:23:06.217292Z

[header]
last_change = 2023-11-15T17:19:40.209695Z
name = "CPad::LookAroundLeftRight"
addr = 0x286af0
type = "short"

[header.args.0]
offset = 0x0
name = "pad"
type = "CPad *"
size = 0x4
