[metadata]
addr = 0x285e80
size = 0x9c
last_change = 2023-11-15T17:25:36.046774Z

[header]
last_change = 2023-11-15T17:19:36.772412Z
name = "CPad::HornJustDown"
addr = 0x285e80
type = "short"

[header.args.0]
offset = 0x0
name = "pad"
type = "CPad *"
size = 0x4
