[metadata]
addr = 0x287580
size = 0x44
last_change = 2023-11-15T17:22:14.797969Z

[header]
last_change = 2023-11-15T17:19:42.416303Z
name = "CPadX__MenuRight"
addr = 0x287580
type = "long"

[header.args.0]
offset = 0x0
name = "a1"
type = "CPad *"
size = 0x4
