[metadata]
addr = 0x285f70
size = 0x2c
last_change = 2023-11-15T17:20:33.232504Z

[header]
last_change = 2023-11-15T17:19:37.096508Z
name = "CPad::CarGunJustUp"
addr = 0x285f70
type = "short"

[header.args.0]
offset = 0x0
name = "pad"
type = "CPad *"
size = 0x4
