[metadata]
addr = 0x285fa0
size = 0x90
last_change = 2023-11-15T17:20:17.905090Z

[header]
last_change = 2023-11-15T17:19:37.216265Z
name = "CPad::GetHandBrake"
addr = 0x285fa0
type = "short"

[header.args.0]
offset = 0x0
name = "pad"
type = "CPad *"
size = 0x4
