[metadata]
addr = 0x299998
size = 0xf54
last_change = 2023-11-15T17:21:40.085169Z

[header]
last_change = 2023-11-15T17:19:45.805525Z
name = "CCam::Process_WheelCam"
addr = 0x299998
type = "long"

[stack_vars.-0xe0]
offset = 0x30
name = "v103"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0xdc]
offset = 0x34
name = "v105"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0xd8]
offset = 0x38
name = "v107"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0xd0]
offset = 0x40
name = "v108"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0xcc]
offset = 0x44
name = "v109"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0xc8]
offset = 0x48
name = "v110"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0xc0]
offset = 0x50
name = "v112"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0xbc]
offset = 0x54
name = "v113"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0xb8]
offset = 0x58
name = "v114"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0xb0]
offset = 0x60
name = "v115"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0xac]
offset = 0x64
name = "v116"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0xa8]
offset = 0x68
name = "v117"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0xa4]
offset = 0x6c
name = "v118"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0xa0]
offset = 0x70
name = "v119"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0x9c]
offset = 0x74
name = "v120"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0x98]
offset = 0x78
name = "v121"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0x94]
offset = 0x7c
name = "v122"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0x90]
offset = 0x80
name = "v123"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0x8c]
offset = 0x84
name = "v124"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0x88]
offset = 0x88
name = "v125"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0x84]
offset = 0x8c
name = "v126"
type = "float"
size = 0x4
addr = 0x299998

[stack_vars.-0x80]
offset = 0x90
name = "v127"
type = "char[64]"
size = 0x40
addr = 0x299998

[stack_vars.-0x40]
offset = 0xd0
name = "v128"
type = "int[4]"
size = 0x10
addr = 0x299998

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4
