[metadata]
addr = 0x36ebd8
size = 0x20
last_change = 2023-11-27T05:25:55.667976Z

[header]
last_change = 2023-11-27T05:25:55.667976Z
name = "CVisibilityComponents::SetElementRenderCallback"
addr = 0x36ebd8
type = "void"

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4

[header.args.1]
offset = 0x1
name = "a2"
type = "int (__fastcall *)(int)"
size = 0x4
