[metadata]
addr = 0x3f4000
size = 0xc
last_change = 2023-11-15T17:20:26.077234Z

[header]
last_change = 2023-11-15T17:19:58.398338Z
name = "CFont::SetFontStyle"
addr = 0x3f4000
type = "long"

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4
