[metadata]
addr = 0x45d980
size = 0x1c8
last_change = 2023-11-27T05:25:04.857517Z

[header]
last_change = 2023-11-27T05:25:04.857517Z
name = "strncmp"
addr = 0x45d980
type = "long"

[header.args.0]
offset = 0x0
name = "$A0"
type = "char *"
size = 0x4

[header.args.1]
offset = 0x1
name = "$A1"
type = "char *"
size = 0x4

[header.args.2]
offset = 0x2
name = "i"
type = "unsigned long"
size = 0x8
